# Generated by Django 3.1 on 2020-09-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M1Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M1QBNum', models.IntegerField(default=0)),
                ('M1QSNum', models.IntegerField(default=0)),
                ('M1QD', models.CharField(max_length=100)),
                ('M1Q', models.CharField(max_length=100)),
                ('One', models.BooleanField(default=False)),
                ('Two', models.BooleanField(default=False)),
                ('Three', models.BooleanField(default=False)),
                ('Four', models.BooleanField(default=False)),
                ('Five', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='M1Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('m1question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.m1question')),
            ],
        ),
    ]
